### ISSUE TITLE
Convertation does'nt work

### ISSUE THREAD

**Issue by JustJabka** [Godlander/objmc#53]
```
Traceback (most recent call last):
  File "C:\Program Files\Python312\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\objmc-main\objmc.py", line 700, in start
    objmc(objs, texs, output, scale, offset, duration, easing, interpolation, colorbehavior, autorotate, autoplay, flipuv, noshadow, nopow)
  File "C:\Users\User\Desktop\objmc-main\objmc.py", line 368, in objmc
    model = open(output[0], "w")
            ^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'potion.json'
```

**Comment by Godlander** [comment]
it says permission denied, thats not an objmc issue but a permission issue with your file system.
