### ISSUE TITLE
Failed to load objmc pack in 1.20.5

### ISSUE THREAD

**Issue by Blobanium** [Godlander/objmc#63]
**Description**
the objmc pack doesnt load into 1.20.5 

**Reproduction**
1. Launch minecraft 1.20.5+
2. try to load objmc pack

**Screenshots**
attach screenshots or videos of the problem

**Environment:**
- Operating System: Windows 11
- 1.20.5
- GPU: Radeon RX 570, CPU: Ryzen 5 7600X
(F3 menu contains important information)

**Additional context**

Heres the error while reloading the pack.

```Caught error loading resourcepacks, removing all selected resourcepacks
java.util.concurrent.CompletionException: java.lang.RuntimeException: could not reload shaders
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at auv.a(SourceFile:69)
	at bpl.d(SourceFile:162)
	at bpp.d(SourceFile:23)
	at bpl.A(SourceFile:136)
	at bpl.bA(SourceFile:121)
	at ffg.c(SourceFile:1275)
	at ffg.f(SourceFile:888)
	at net.minecraft.client.main.Main.main(SourceFile:265)
Caused by: java.lang.RuntimeException: could not reload shaders
	at gdi.c(SourceFile:543)
	at gdi$1.a(SourceFile:421)
	at gdi$1.a(SourceFile:398)
	at auu.a(SourceFile:13)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
	... 9 more
Caused by: ali: Invalid shaders/core/particle.json: Couldn't compile vertex program (vanilla, particle) : Vertex shader failed to compile with the following errors:
ERROR: 0:22: error(#202) No matching overloaded function found: fog_distance
ERROR: error(#273) 1 compilation errors.  No code generated
	at ali.a(SourceFile:48)
	at ged.<init>(SourceFile:176)
	at gdi.c(SourceFile:481)
	... 13 more
Caused by: java.io.IOException: Couldn't compile vertex program (vanilla, particle) : Vertex shader failed to compile with the following errors:
ERROR: 0:22: error(#202) No matching overloaded function found: fog_distance
ERROR: error(#273) 1 compilation errors.  No code generated
	at ezn.b(SourceFile:69)
	at ezn.a(SourceFile:51)
	at ged.a(SourceFile:214)
	at ged.<init>(SourceFile:161)
	... 14 more```

**Comment by vadim-soude** [comment]
Try this fix : https://github.com/Godlander/objmc/pull/64 👍
